{% set name = "mscxyz" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c981fe202935227d34a5eef787d3943506c2953b460764693aab163994c6fdeb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - lxml
    - python >=3.6
    - termcolor
    - tmep >=2.0.1

test:
  imports:
    - mscxyz
  commands:
    - pip check
    - mscx-manager -h
  requires:
    - pip

about:
  home: https://github.com/Josef-Friedrich/mscxyz
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A command line tool to manipulate the XML based *.mscX and *.mscZ files of the notation software MuseScore.
  description: |
    Manipulate the XML based mscx files of the notation software MuseScore.
  doc_url: https://mscxyz.readthedocs.io/
  dev_url: https://github.com/Josef-Friedrich/mscxyz

extra:
  recipe-maintainers:
    - thewchan
