{% set name = "mscxyz" %}
{% set version = "4.0.0" %}
{% python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ace35c10c0d046022c1325030cd5dfbee3a101a1c0e91388ea6d7ed24d1ad381

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - musescore-manager=mscxyz.cli:execute

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry-core
  run:
    - python >={{ python_min }}
    - lxml >=5.3.0,<6.0.0
    - termcolor >=2.5.0,<3.0.0
    - tmep >=3.0.0,<4.0.0
    - lxml-stubs >=0.5.1,<0.6.0
    - shtab >=1.7.1,<2.0.0

test:
  imports:
    - mscxyz
  commands:
    - pip check
    - musescore-manager -h
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Josef-Friedrich/mscxyz
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A command line tool to manipulate the XML based *.mscX and *.mscZ files of the notation software MuseScore.
  description: |
    Manipulate the XML based mscx files of the notation software MuseScore.
  doc_url: https://mscxyz.readthedocs.io/
  dev_url: https://github.com/Josef-Friedrich/mscxyz

extra:
  recipe-maintainers:
    - thewchan
