{% set name = "mscxyz" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cbe4d70b4824b7078b871ecd3547457fd6c7e322c1d96d6c13968c0733e22927

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mscx-manager=mscxyz:execute

requirements:
  host:
    - pip
    - python >=3.8
    - poetry >=1.2.0b2
  run:
    - lxml >=5.0.0,<6.0.0
    - python >=3.8
    - termcolor >=2.4.0,<3.0.0
    - tmep >=2.3.3,<2.4.0
    - lxml-stubs >=0.4.0,<0.5.0

test:
  imports:
    - mscxyz
  commands:
    - pip check
    - mscx-manager -h
  requires:
    - pip

about:
  home: https://github.com/Josef-Friedrich/mscxyz
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A command line tool to manipulate the XML based *.mscX and *.mscZ files of the notation software MuseScore.
  description: |
    Manipulate the XML based mscx files of the notation software MuseScore.
  doc_url: https://mscxyz.readthedocs.io/
  dev_url: https://github.com/Josef-Friedrich/mscxyz

extra:
  recipe-maintainers:
    - thewchan
